### PR TITLE
Configure Spotless code formatter.

### PR DESCRIPTION
**Pull request by blu28**
Causes format violations to fail the build, but also can be used to automatically format the files.

### CODE REVIEW

**Comment by blu28** [comment]
The initial PR worked locally. All of the subsequent commits were to get it working with the build check workflow.

**Comment by blu28** [comment]
I removed the formatting changes since it created many conflicts. We can wait until after the next comp, and then do the reformat of the files in main then.

**Comment by kcq888** [comment]
Please let us take a look what you are doing first. Need to understand what the Spotless code formatter do.

**Comment by blu28** [comment]
Withdrawing this PR until I can get the ratchetfrom working.

**Pull request closed without merging**
